theme: readthedocs
site_name: SIMA Documentation
google_analytics: ['UA-35617728-3', 'auto']
site_dir: E:\Papyrus\Gestor Multimedia\RC\es-ES
pages: 
- 'Inicio': 'index.md'
- 'Gestor multimedia': 'Gestor multimedia.md'
- 'Versiones': 'Versiones.md'

